# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0007_bookcatalogue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bookcatalogue',
            name='book_id',
        ),
        migrations.AddField(
            model_name='bookcatalogue',
            name='book_price',
            field=models.PositiveIntegerField(default=100),
            preserve_default=False,
        ),
    ]
