# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-30 09:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic_app', '0008_auto_20171130_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookcatalogue',
            name='quantity',
            field=models.PositiveIntegerField(default=5),
            preserve_default=False,
        ),
    ]
